name: mcauthlib
description: Mojang's Yggdrasil authentication for Dart.
version: 1.0.0
repository: https://github.com/GiftShower/mcauthlib
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
   path: ^1.8.0
   json_annotation: ^4.3.0
   http: ^0.13.4


dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.1.4
  json_serializable: ^6.0.0